export const ACTION_CONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_DATA_UPDATE: 'LOGIN_DATA_UPDATE',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',

  //AUTH DATA AND PAGE INDEX
  SET_PAGE_INDEX: 'SET_PAGE_INDEX',
  UPDATE_SURVEY_FORM: 'UPDATE_SURVEY_FORM',
  RESET_PAGE_AND_AUTH_DATA: 'RESET_PAGE_AND_AUTH_DATA',

  // STATE
  UPDATE_STATE_LIST: 'UPDATE_STATE_LIST',
  CLEAR_STATE_LIST: 'CLEAR_STATE_LIST',

  // DISTRICTS
  UPDATE_DISTRICTS_LIST: 'UPDATE_DISTRICTS_LIST',
  CLEAR_DISTRICTS_LIST: 'CLEAR_DISTRICTS_LIST',

  // BASTI
  UPDATE_BASTI_LIST: 'UPDATE_BASTI_LIST',
  CLEAR_BASTI_LIST: 'CLEAR_BASTI_LIST',

  UPDATE_SURVEY: 'UPDATE_SURVEY',
  CLEAR_SURVEY: 'CLEAR_SURVEY',

  // Survey status
  UPDATE_SURVEY_STATUS: 'UPDATE_SURVEY_STATUS',
  CLEAR_SURVEY_STATUS: 'CLEAR_SURVEY_STATUS',
  ADD_COMPLETED_SURVEY_COUNT: 'ADD_COMPLETED_SURVEY_COUNT',
  ADD_INCOMPLETED_SURVEY_COUNT: 'ADD_INCOMPLETED_SURVEY_COUNT',
  REMOVE_INCOMPLETED_SURVEY_COUNT: 'REMOVE_INCOMPLETED_SURVEY_COUNT',
  // Saved Surveys
  UPDATE_SAVED_SURVEYS: 'UPDATE_SAVED_SURVEYS',
  ADD_SAVED_SURVEY_COUNT: 'UPDATE_SAVED_SURVEY_COUNT',
  REMOVE_SAVED_SURVEY_COUNT: 'REMOVE_SAVED_SURVEY_COUNT',
};
