export const ACTION_CONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',

  //AUTH DATA AND PAGE INDEX
  SET_PAGE_INDEX: 'SET_PAGE_INDEX',
  SAVE_AUTH_DATA: 'SAVE_AUTH_DATA',
  RESET_PAGE_AND_AUTH_DATA: 'RESET_PAGE_AND_AUTH_DATA',

  // BASTI
  UPDATE_BASTI_LIST: 'UPDATE_BASTI_LIST',
  CLEAR_BASTI_LIST: 'CLEAR_BASTI_LIST',
};
