export const ACTION_CONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_DATA_UPDATE: 'LOGIN_DATA_UPDATE',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',

  //AUTH DATA AND PAGE INDEX

  // states
  UPDATE_STATE_LIST: 'UPDATE_STATE_LIST',
  CLEAR_STATE_LIST: 'CLEAR_STATE_LIST',

  // districts
  UPDATE_DISTRICTS_LIST: 'UPDATE_DISTRICTS_LIST',
  CLEAR_DISTRICTS_LIST: 'CLEAR_DISTRICTS_LIST',

  // basti
  UPDATE_BASTI_LIST: 'UPDATE_BASTI_LIST',
  CLEAR_BASTI_LIST: 'CLEAR_BASTI_LIST',

  // for current survey
  UPDATE_CURRENT_SURVEY: 'UPDATE_CURRENT_SURVEY',
  CLEAR_CURRENT_SURVEY: 'CLEAR_CURRENT_SURVEY',

  // overall survey status
  CLEAR_SURVEY_STATUS: 'CLEAR_SURVEY_STATUS',
  ADD_COMPLETED_SURVEY_COUNT: 'ADD_COMPLETED_SURVEY_COUNT',
  ADD_INCOMPLETED_SURVEY_COUNT: 'ADD_INCOMPLETED_SURVEY_COUNT',
  REMOVE_INCOMPLETED_SURVEY_COUNT: 'REMOVE_INCOMPLETED_SURVEY_COUNT',

  // Saved Surveys
  UPDATE_SAVED_SURVEYS: 'UPDATE_SAVED_SURVEYS',
  ADD_SAVED_SURVEY_COUNT: 'UPDATE_SAVED_SURVEY_COUNT',
  REMOVE_SAVED_SURVEY_COUNT: 'REMOVE_SAVED_SURVEY_COUNT',
};
