export const ROUTES = {
  AUTH: {
    SPLASHSCREEN: 'SPLASHSCREEN',
    LOGINSCREEN: 'LOGINSCREEN',
    OTPSCREEN: 'OTPSCREEN',
    VOLUNTEERSIGNUPSCREEN: 'VOLUNTEERSIGNUPSCREEN',
    DASHBOARDSCREEN: 'DASHBOARDSCREEN',
    VOLUNTEERWELCOMESCREEN: 'VOLUNTEERWELCOMESCREEN',
    SELECTAUDIENCESCREEN: 'SELECTAUDIENCESCREEN',
    VOLUNTEERPARENTALORGSCREEN: 'VOLUNTEERPARENTALORGSCREEN',
    STUDENTENROLLMENTSCREEN: 'STUDENTENROLLMENTSCREEN',
    SURVEYSCREEN: 'SURVEYSCREEN',
    CENTREQUESTIONSCREEN: 'CENTREQUESTIONSCREEN',
    PURV_ABHIBHAVAK_SCREEN: 'PURV_ABHIBHAVAK_SCREEN',
    VARTAAMAAN_ABHIBHAVAK_SCREEN: 'VARTAAMAAN_ABHIBHAVAK_SCREEN',
    TEACHERQUESTONSSCREEN : "TEACHERQUESTONSSCREEN" ,
    KENDRASANCHALAKSCREEN : "KENDRASANCHALAKSCREEN" ,
    BASTIQUESTIONS : "BASTIQUESTIONS" ,
    PRABUDDHAJANQUESTIONS : "PRABUDDHAJANQUESTIONS"
  },
};
