export const ROUTES = {
  AUTH: {
    SPLASHSCREEN: 'SPLASHSCREEN',
    LOGINSCREEN: 'LOGINSCREEN',
    OTPSCREEN: 'OTPSCREEN',
    VOLUNTEERSIGNUPSCREEN: "VOLUNTEERSIGNUPSCREEN" ,
    VOLUNTEERWELCOMESCREEN:"VOLUNTEERWELCOMESCREEN"
  },
};
