export const ROUTES = {
  AUTH: {
    SPLASHSCREEN: 'SPLASHSCREEN',
    LOGINSCREEN: 'LOGINSCREEN',
    OTPSCREEN: 'OTPSCREEN',
    VOLUNTEERSIGNUPSCREEN: "VOLUNTEERSIGNUPSCREEN" ,
    VOLUNTEERWELCOMESCREEN:"VOLUNTEERWELCOMESCREEN" ,
    VOLUNTEERSURVEYSCREEN1:"VOLUNTEERSURVEYSCREEN1",
  
    VOLUNTEERPARENTALORGSCREEN: 'VOLUNTEERPARENTALORGSCREEN',
  },
};
